### PR TITLE
Ability to show error message, show help and exit

### PR DESCRIPTION
**Pull request by untitaker**
I think this would cover quite a lot of usecases of #3.

If you think this is worth expanding, i will add documentation, tests etc

### CODE REVIEW

**Comment by DasIch** [comment]
Yeah, I think this is a useful approach. Though I think it's sufficient to just raise UsageError in user code to achieve the desired effect as opposed to `abort()`.

**Comment by untitaker** [comment]
Added. Not sure how to integrate this into the tutorial. It doesn't really fit in any chapter, i propose a page for input validation.

**Comment by untitaker** [comment]
bump

**Comment by untitaker** [comment]
This has been superseded by #9.

**Pull request closed without merging**
